// Generated by tools/derivations/expected_values.py. Do not edit.
// clang-format off
#pragma once

#include <array>

namespace expected {

namespace adaptive_central_differentiation_function_test {
inline constexpr double output_test = 2.0;
}

namespace adaptive_integration_function_test {
inline constexpr double output_test = 0.003993143831817661;
}

namespace brent_solver_function_test {
inline constexpr double output_test = 2.23606797749979;
}

namespace gaussian_distribution_test {
inline constexpr double cdf_test = 0.5735637353767205;
}

namespace general_linear_model_test {
inline constexpr double get_conditional_variance_test_step_one = 109.19818826032954;
inline constexpr double get_conditional_variance_test_step_two = 218.08310689556842;
inline constexpr double get_conditional_variance_zero_mu_limit_test_near_zero_mu_step_one = 0.002500000000002751;
inline constexpr double get_conditional_variance_zero_mu_limit_test_zero_mu_step_one = 0.0025000000000000005;
inline constexpr double get_conditional_variance_zero_mu_limit_test_zero_mu_step_two = 0.005000000000000001;
inline constexpr double get_unconditional_variance_test = 38063.83819014668;
}

namespace hitting_time_density_test {
inline constexpr double hitting_time_density_output_test = 0.4304600561745479;
}

namespace hitting_time_ornstein_uhlenbeck_test {
inline constexpr double hitting_time_core_output_test = 0.18637397603941006;
inline constexpr double optimal_trading_f_core_output_test = 0.9185122844014574;
inline constexpr double optimal_trading_g_core_output_test = 1.0778841508846315;
inline constexpr double optimal_trading_l_core_output_test = 0.29826086956521736;
}

namespace kalman_filter_state_test {
inline constexpr std::array<std::array<double, 3>, 3> kca_statesupdate_current_state_test_current_state_covariance = {{{0.009269818720519449, 0.0, 0.0}, {0.0, 0.001, 0.0}, {0.0, 0.0, 0.001}}};
inline constexpr std::array<double, 3> kca_statesupdate_current_state_test_current_state_mean = {10.3000765492722, 0.0, 0.0};
inline constexpr std::array<std::array<double, 1>, 1> kca_statesupdate_current_state_test_predicted_observation_covariance = {{{0.13695229227341849}}};
inline constexpr std::array<double, 1> kca_statesupdate_current_state_test_predicted_observation_mean = {10.301048359829961};
inline constexpr std::array<std::array<double, 3>, 3> kca_statesupdate_predicted_state_test_predicted_state_covariance = {{{0.12695229227341848, 0.0, 0.0}, {0.0, 0.001, 0.0}, {0.0, 0.0, 0.001}}};
inline constexpr std::array<double, 3> kca_statesupdate_predicted_state_test_predicted_state_mean = {10.301048359829961, 0.0, 0.0};
}

namespace kalman_filter_test {
inline constexpr std::array<std::array<double, 3>, 3> current_state_calculate_covariance_test_current_state_covariance = {{{4.7105773280001206e-05, 0.0, 0.0}, {0.0, 0.001, 0.0}, {0.0, 0.0, 0.001}}};
inline constexpr std::array<double, 3> current_state_calculate_mean_test_current_state_mean = {1.3108695137597879, 0.0, 0.0};
inline constexpr std::array<std::array<double, 1>, 1> predicted_observation_calculate_covariance_test_predicted_observation_covariance = {{{0.0137912692000676}}};
inline constexpr std::array<std::array<double, 1>, 3> predicted_observation_calculate_kalman_gain_test_kalman_gain = {{{0.9965413980872554}, {0.0}, {0.0}}};
inline constexpr std::array<double, 1> predicted_observation_calculate_mean_test_predicted_observation_mean = {1.330986};
inline constexpr std::array<std::array<double, 3>, 3> predicted_state_calculate_covariance_test_predicted_state_covariance = {{{0.013744, 0.0, 0.0}, {0.0, 0.001, 0.0}, {0.0, 0.0, 0.001}}};
inline constexpr std::array<double, 3> predicted_state_calculate_mean_test_predicted_state_mean = {1.3309855249349998, 0.0, 0.0};
}

namespace kca_test {
inline constexpr std::array<std::array<double, 3>, 3> get_initialized_kca_state_test_current_state_covariance = {{{0.0, 0.0, 0.0}, {0.0, 0.0, 0.0}, {0.0, 0.0, 0.0}}};
inline constexpr std::array<double, 3> get_initialized_kca_state_test_current_state_mean = {10.27645, 0.0, 0.0};
inline constexpr std::array<std::array<double, 3>, 1> get_initialized_kca_state_test_observation_matrix = {{{1.0, 0.0, 0.0}}};
inline constexpr double get_initialized_kca_state_test_observation_offset = 0.0;
inline constexpr std::array<std::array<double, 3>, 3> get_initialized_kca_state_test_transition_covariance = {{{5e-05, 0.000125, 0.00016666666666666666}, {0.000125, 0.0003333333333333333, 0.0005}, {0.00016666666666666666, 0.0005, 0.001}}};
inline constexpr std::array<std::array<double, 3>, 3> get_initialized_kca_state_test_transition_matrix = {{{1.0, 1.0, 0.5}, {0.0, 1.0, 1.0}, {0.0, 0.0, 1.0}}};
inline constexpr std::array<std::array<double, 3>, 3> get_updated_kca_state_test_current_state_covariance = {{{0.009269818720519449, 0.0, 0.0}, {0.0, 0.001, 0.0}, {0.0, 0.0, 0.001}}};
inline constexpr std::array<double, 3> get_updated_kca_state_test_current_state_mean = {10.3000765492722, 0.0, 0.0};
inline constexpr std::array<std::array<double, 3>, 1> get_updated_kca_state_test_observation_matrix = {{{1.0, 0.0, 0.0}}};
inline constexpr double get_updated_kca_state_test_observation_offset = 0.0;
inline constexpr std::array<std::array<double, 3>, 3> get_updated_kca_state_test_transition_covariance = {{{0.12695229227341848, 0.0, 0.0}, {0.0, 0.001, 0.0}, {0.0, 0.0, 0.001}}};
inline constexpr std::array<std::array<double, 3>, 3> get_updated_kca_state_test_transition_matrix = {{{1.0011961162353782, 1.0, 0.5}, {0.0, 1.0, 1.0}, {0.0, 0.0, 1.0}}};
}

namespace optimal_mean_reversion_test {
inline constexpr double method_a_stop_loss_output_test = -132.55275540985355;
inline constexpr double method_above_v_output_test = 0.53;
inline constexpr double method_above_v_stop_loss_output_test = 0.55;
inline constexpr double method_b_output_test = 135.51123787337457;
inline constexpr double method_b_stop_loss_output_test = 187.80766789903623;
inline constexpr double method_below_v_output_test = 0.4033891920689373;
inline constexpr double method_below_v_stop_loss_output_test = 0.46932190365804316;
inline constexpr double method_d_output_test = -129.09611238885014;
inline constexpr double method_d_stop_loss_output_test = -61.832566646309694;
inline constexpr double method_f_output_test = 5.804824006148855;
inline constexpr double method_g_output_test = 163.61682127334302;
}

namespace optimal_trading_levels_test {
inline constexpr double optimal_entry_level_exponential_output_test = 1.2368865665357225;
inline constexpr double optimal_entry_level_output_test = 0.115681099001361;
inline constexpr double optimal_entry_level_stop_loss_output_test = 0.13092977518133622;
inline constexpr double optimal_entry_lower_stop_loss_output_test = 0.10763308326813295;
inline constexpr double optimal_exit_level_exponential_output_test = 1.40929954132349;
inline constexpr double optimal_exit_level_output_test = 0.46683586991445225;
inline constexpr double optimal_exit_level_stop_loss_output_test = 0.455190759905994;
}

namespace ornstein_uhlenbeck_likelihood_calculate_test {
inline constexpr double components_test_lag_sum = 3.5;
inline constexpr double components_test_lag_sum_squared = 3.375;
inline constexpr double components_test_lead_lag_sum_product = 3.25;
inline constexpr double components_test_lead_sum = 4.0;
inline constexpr double components_test_lead_sum_squared = 4.125;
inline constexpr unsigned components_test_n_obs = 6u;
inline constexpr double parameter_test_alpha = 0.7205461547480593;
inline constexpr double parameter_test_mu = 0.8947368421052632;
inline constexpr double parameter_test_sigma = 0.5163352372797948;
}

namespace ornstein_uhlenbeck_likelihood_update_test {
inline constexpr double components_test_lag_sum = 4.5;
inline constexpr double components_test_lag_sum_squared = 4.375;
inline constexpr double components_test_lead_lag_sum_product = 4.0;
inline constexpr double components_test_lead_sum = 4.75;
inline constexpr double components_test_lead_sum_squared = 4.6875;
inline constexpr unsigned components_test_n_obs = 7u;
inline constexpr double parameter_test_alpha = 0.8266785731844672;
inline constexpr double parameter_test_mu = 0.8240740740740741;
inline constexpr double parameter_test_sigma = 0.5007098524429631;
}

namespace ornstein_uhlenbeck_model_test {
inline constexpr double get_conditional_variance_output_test_step_one = 0.0024506600529797997;
inline constexpr double get_conditional_variance_output_test_step_two = 0.004805228350835264;
inline constexpr double get_conditional_variance_zero_alpha_limit_test_near_zero_alpha_step_one = 0.0024999999999972505;
inline constexpr double get_conditional_variance_zero_alpha_limit_test_zero_alpha_step_one = 0.0025000000000000005;
inline constexpr double get_conditional_variance_zero_alpha_limit_test_zero_alpha_step_two = 0.005000000000000001;
inline constexpr double get_mean_output_test = 0.5;
inline constexpr double get_unconditional_variance_output_test = 0.0625;
}

namespace ou_model_test {
inline constexpr double hitting_time_density_output_test = 0.4304600561745479;
inline constexpr double ornstein_uhlenbeck_maximum_likelihood_output_test_alpha = 2.917770732084274;
inline constexpr double ornstein_uhlenbeck_maximum_likelihood_output_test_mu = 0.7;
inline constexpr double ornstein_uhlenbeck_maximum_likelihood_output_test_sigma = 1.0390260684271504;
}

namespace semi_infinite_integration_function_test {
inline constexpr double output_test = 0.3060313334578499;
}

namespace solver_bounds_test {
inline constexpr double lower_solver_bound_output_test = 0.4280214644292698;
inline constexpr double upper_solver_bound_output_test = 0.6495785355707301;
}

namespace trading_levels_test {
inline constexpr double entry_level_exponential_output_test = 1.2368865665357225;
inline constexpr double entry_level_lower_bound_stop_loss_output_test = 0.10763308326813295;
inline constexpr double entry_level_output_test = 0.115681099001361;
inline constexpr double entry_level_stop_loss_output_test = 0.13092977518133622;
inline constexpr double exit_level_exponential_output_test = 1.40929954132349;
inline constexpr double exit_level_output_test = 0.46683586991445225;
inline constexpr double exit_level_stop_loss_output_test = 0.455190759905994;
inline constexpr double level_ordering_chain_test_a_star = 0.10763308326819016;
inline constexpr double level_ordering_chain_test_b_star = 0.46683586991445225;
inline constexpr double level_ordering_chain_test_b_star_stop_loss = 0.455190759905994;
inline constexpr double level_ordering_chain_test_d_star = 0.1309297751814221;
}

} // namespace expected
