name: Run tests

on: [push]
jobs:
  test:
    runs:
      using: 'docker'
      image: 'Dockerfile'
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
    - name: Run tests
      run: ./tests
