name: Run tests
      
on: [push]

jobs:
  test:
    runs-on: ubuntu-20.04
    container:
      image: gcc:12
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
    - name: setup.sh permissions
      run: chmod +x ./setup.sh
    - name: Bootstrap environment
      run: ./setup.sh
    - name: Create build files
      run: cmake .
    - name: Build application
      run: cmake --build . --target install
    - name: Run tests
      run: ./tests
